import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Studio Mighty Mighty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.header}>
          <div className={styles.main_holder}>
            <ul className={styles.nav}>
              <li className={styles.active}><a href="/"><div></div><span>Work</span></a></li>
              <li><a href="/about"><div></div><span>About</span></a></li>
              <li><a href="/contact"><div></div><span>Contact</span></a></li>
            </ul>
            <div className={styles.logo}>
              <a href="/">
                <img src="/mark.svg"/>
              </a>
            </div>
          </div>
        </div>

        <div className={styles.site_header_content}>

          <div className={styles.home_top_section}>
            <div className={styles.mightymighty}>MIGHTY MIGHTY</div>
          </div>

          <div className={styles.home_large_text}>Helping brands figure out who they are and who they want to <strong>become</strong>.</div>

          <div className={styles.collage}>
            <img src="/collage.png"/>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
